theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: Orlando .NET User Group (ONETUG)
description: [A short description of your site's purpose]
logo: ~/onetuglogo.jpg
show_downloads: "false"
