theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: Orlando .NET User Group (ONETUG)
description: A Central Florida based community centered around the .NET ecosystem
logo: onetuglogo.jpg
show_downloads: false