theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
plugins:
  - jekyll-redirect-from
title: ONETUG
logo: onetuglogo.jpg
show_downloads: false
redirect_from: /twitter
redirect_to: http://twitter.com/onetug