theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
title: Orlando .NET User Group (ONETUG)
description: ONETUG is based in Central Florida. We're a community centered around the .NET ecosystem.
logo: onetuglogo.jpg
show_downloads: "false"
